# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solveittest',
                'doc_host': 'https://Gtombri.github.io',
                'git_url': 'https://github.com/Gtombri/solveittest',
                'lib_path': 'solveittest'},
  'syms': {'solveittest.core': {'solveittest.core.foo': ('core.html#foo', 'solveittest/core.py')}}}
